version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: PHP_Project
      MYSQL_USER: etu
      MYSQL_PASSWORD: coucou
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html